on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  electron-build:
    name: Build and Test Electron App
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: electron
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        node_version:
          - 17
        architecture:
          - x64
          # - x86
          # - arm64
        # an extra windows-x86 run:
        # include:
        # - os: windows-2016
        # node_version: 17
        # architecture: x86
    # name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "yarn"
          cache-dependency-path: "electron/yarn.lock"
      - run: yarn install --frozen-lockfile # optional, --immutable
      - run: yarn test

  electron-run-linters:
    name: Run Electron Linters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: electron

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
